## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

services:
 - postgresql
 - mysql

os:
  - linux
#  - osx

julia:
  - nightly

env:
  - POSTGRESQL_VERSION=9.6 PGHOST="/var/run/postgresql"

before_install:
  # PostgreSQL 9.6.6
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
  - psql --version
  - psql -U postgres -tc 'SHOW server_version'
  - psql -U postgres -c '\conninfo'
  # MySQL
  - mysql --version
  - mysql -e 'show variables like "socket";' -uroot
  - mysql -e 'CREATE DATABASE mysqltest;' -uroot
  - mysql -e 'GRANT ALL PRIVILEGES ON mysqltest.* TO "root"@"localhost" IDENTIFIED BY ""' -uroot

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

before_script: # homebrew for mac
  - export OLD_PATH=$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mysql_config --libs | cut -d ' ' -f1 | sed 's/-L//'`
#  - if [ "$TRAVIS_OS_NAME" == osx ]; then brew install mysql          ; fi
#  - if [ "$TRAVIS_OS_NAME" == osx ]; then mysql.server start          ; fi

## uncomment the following lines to override the default test script

script:
  # DataStreams not compatible with julia 0.6 - https://github.com/wookay/DataStreams.jl/pull/1
  - julia -e 'using Pkg; Pkg.clone("https://github.com/wookay/DataStreams.jl.git"); Pkg.checkout("DataStreams", "fix_07"); using DataStreams'
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Octo"); Pkg.test("Octo"; coverage=true)'

after_script:
  - export LD_LIBRARY_PATH=$OLD_PATH
  - unset OLD_PATH

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Octo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Octo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
