authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "Octo"
uuid = "c980e7ac-2ea9-11e8-1f3c-e1d64ddcfff6"
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
