name = "Octo"
uuid = "16905944-f982-529b-abb2-b839f98f160b"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.2.14-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Jive = "0.3"
LibPQ = "1.18"
SQLite = "1.6, 1.8"
MySQL = "1.4, 1.5"
MariaDB_Connector_C_jll = "3.3"
DuckDB = "1.2"
DataFrames = "1.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
MariaDB_Connector_C_jll = "aabc7e14-95f1-5e66-9f32-aea603782360"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[targets]
test = ["Test", "Jive", "LibPQ", "SQLite", "MySQL", "MariaDB_Connector_C_jll", "DuckDB", "DataFrames", "UUIDs"]
